apiVersion: v1
kind: Pod
metadata:
  name: irsa-demo
  namespace: irsa-demo
  labels:
    app: irsa-test
spec:
  serviceAccountName: irsa-sa  
  containers:
    - name: awscli
      image: amazonlinux:2
      command: ["/bin/sh", "-c"]
      args:
        - yum install -y aws-cli && \
          aws sts get-caller-identity && \
          sleep 3600
