# Use only if the pod also needs access to Kubernetes resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: irsa-role
  namespace: irsa-demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: irsa-rolebinding
  namespace: irsa-demo
subjects:
  - kind: ServiceAccount
    name: irsa-sa
    namespace: irsa-demo
roleRef:
  kind: Role
  name: irsa-role
  apiGroup: rbac.authorization.k8s.io
